// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/lib/js/src/jest.js");

Jest.describe("some test", (function (param) {
        return Jest.test("passes!", (function (param) {
                      return Jest.Expect.toBe(false, Jest.Expect.expect(true));
                    }));
      }));

/*  Not a pure module */
